---
- name: add grafana 8.1.0 version instead of latest 8.3.0 to use with Notification channels
  shell:  "cd /tmp/ ; wget https://dl.grafana.com/oss/release/grafana-8.1.0-1.x86_64.rpm ; sudo yum install -y grafana-8.1.0-1.x86_64.rpm"

- name: install grafana
  yum:
    name: grafana
    state:  latest
    update_cache: true

- name: start service grafana-server
  service:
    name: grafana-server
    state: started
    enabled:  true

- name: reset admin passwd
  shell : "grafana-cli admin reset-admin-password {{ admin_password }}"

- name: prometheus datasource
  grafana_datasource:
    name: "prometheus-ds"
    grafana_url: "http://127.0.0.1:3000"
    grafana_user: "admin"
    grafana_password: "{{ admin_password }}"
    ds_type: "prometheus"
    ds_url: "http://127.0.0.1:9090"

- name: dashboard template download
  get_url:
    url: https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json
    dest: /var/lib/grafana/node-exporter.json
    mode: '0755'

- name: dashboard deploy
  template:
    src: dashboard.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yml
    mode: 0755
  notify: restart grafana

- name: Slack notification channel
  community.grafana.grafana_notification_channel:
    uid: slack
    name: slack
    type: slack
    slack_url:  https://hooks.slack.com/services/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
    grafana_url: "http://127.0.0.1:3000"
    grafana_user: "admin"
    grafana_password: "{{ admin_password }}"
  notify: restart grafana